language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t gulrezaktharkhan/docker-react -f Dockerfile.dev . 

script:
  - docker run gulrezaktharkhan/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-test-new"
  env: "DockerTestNew-env"
  bucket_name: "elasticbeanstalk-eu-west-1-832409163536"
  bucket_path: "docker-test-new"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"